version: '3.7'
services:

  middleware:
    container_name: ipsec-middleware
    build:
      context: ipsec-backend
      dockerfile: Dockerfile
    volumes:
      - shared-ipsec:/opt/ipsec/
      - shared-super:/opt/super/
      - shared-bird:/opt/bird/
    restart: always
    command: /ipsec_backend

  frontend:
    container_name: ipsec-frontend
    build:
      context: ipsec-ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    command: nginx -g "daemon off;"

volumes:
   shared-super:
   shared-ipsec:
   shared-bird:
