version: '3.7'
services:
  middleware:
    container_name: ipsec-middleware
    build:
      context: ipsec-backend
      dockerfile: Dockerfile
    volumes:
      - shared-ipsec:/opt/ipsec/
      - shared-super:/opt/super/
      - shared-bird:/opt/bird/
    restart: always
    ports:
      - "8000:8000"
    command: /ipsec_backend

volumes:
   shared-super:
   shared-ipsec:
   shared-bird:
