version: '3.7'
services:

  middleware:
    container_name: ipsec-middleware
    build:
      context: ipsec-backend
      dockerfile: Dockerfile
    volumes:
      - environment_shared-ipsec:/opt/ipsec/
      - environment_shared-super:/opt/super/
      - environment_shared-bird:/opt/bird/
    restart: always
    command: /ipsec_backend
    environment:
      - SWITCH_ADDRESS=10.5.0.10
    networks:
      ipsec:
        ipv4_address: 10.5.0.201

  frontend:
    container_name: ipsec-frontend
    build:
      context: ipsec-ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    command: nginx -g "daemon off;"
    environment:
      - MIDDLEWARE_HOSTNAME=10.5.0.201
      - MIDDLEWARE_PORT=8000
    networks:
      ipsec:
        ipv4_address: 10.5.0.202


networks:
  ipsec:
    name: ipsec
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ipsec_br
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  environment_shared-super:
    external: true
  environment_shared-ipsec:
    external: true
  environment_shared-bird:
    external: true
