---
- name: configure an example tunnel
  hosts: localhost
  vars_files: ../../vars.yml
  tasks:

  - name: configure the hardware vrf
    uri:
      url: https://localhost/restconf/data/sico-ipsec:api/vrf=1
      method: PATCH
      status_code: [204]
      force_basic_auth: yes
      user: "{{ sico_username }}"
      password: "{{ sico_password }}"
      src: hw.json
      validate_certs: no
