# Copyright (c) 2021 Cisco and/or its affiliates
#
# This software is licensed under the terms of the Cisco Sample Code License (CSCL)
# available here: https://developer.cisco.com/site/license/cisco-sample-code-license/

---
- name: configure an example tunnel
  hosts: localhost
  vars_files: ../../vars.yml
  tasks:

  - name: configure the hardware vrf
    uri:
      url: https://localhost/restconf/data/ipsecclient:api/vrf=1
      method: PATCH
      status_code: [204]
      force_basic_auth: yes
      user: "{{ ipsecclient_username }}"
      password: "{{ ipsecclient_password }}"
      src: hw.json
      validate_certs: no
