version: '3.7'
services:
  ipsec-1:
    container_name: site1
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site1
    volumes:
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime
      - shared-ipsec:/etc/swanctl/conf.d/
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.5.0.101

  supervisor-1:
    container_name: supervisor1
    pid: service:ipsec-1
    network_mode: service:ipsec-1
    build:
      context: supervisor
      dockerfile: Dockerfile
      args:
        CONFIG: site1
    volumes:
      - shared-super:/etc/supervisor.d/
    privileged: yes
    restart: always

  ip-utils-1:
    container_name: utils1
    pid: service:ipsec-1
    image: alpine
    volumes:
      - shared-ipsec:/opt/ipsec/
      - shared-super:/opt/super/
      - shared-bird:/opt/bird/
    restart: always
    network_mode: service:ipsec-1
    command: sleep 3600

  bird-1:
    container_name: bird1
    pid: service:ipsec-1
    network_mode: service:ipsec-1
    volumes:
      - shared-bird:/etc/bird.d/

    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site1

  ipsec-2:
    container_name: site2
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site2
    volumes:
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.5.0.102

  bird-2:
    container_name: bird2
    pid: service:ipsec-2
    network_mode: service:ipsec-2
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site2

  ipsec-3:
    container_name: site3
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site3
    volumes:
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.5.0.103

  bird-3:
    container_name: bird3
    pid: service:ipsec-3
    network_mode: service:ipsec-3
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site3

  ipsec-4:
    container_name: site4
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site4
    volumes:
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.5.0.104

  bird-4:
    container_name: bird4
    pid: service:ipsec-4
    network_mode: service:ipsec-4
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site4



networks:
  ipsec:
    name: ipsec
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ipsec_br
    ipam:
     config:
       - subnet: 10.5.0.0/16

volumes:
   shared-super:
   shared-ipsec:
   shared-bird: