---
- name: configure an example tunnel
  hosts: localhost
  vars_files: ../../vars.yml
  tasks:

  - name: delete a previous software vrf if exists
    ignore_errors: yes
    uri:
      url: https://localhost/restconf/data/sico-ipsec:api/vrf=3
      method: DELETE
      force_basic_auth: yes
      user: "{{ sico_username }}"
      password: "{{ sico_password }}"
      validate_certs: no

  - name: template the configuration json
    ansible.builtin.template:
      src: sw_create.json.j2
      dest: sw_create.json

  - name: create a software vrf
    uri:
      url: https://localhost/restconf/data/sico-ipsec:api/vrf
      method: POST
      status_code: [200, 201]
      force_basic_auth: yes
      user: "{{ sico_username }}"
      password: "{{ sico_password }}"
      src: sw_create.json
      validate_certs: no
