# Copyright (c) 2021 Cisco and/or its affiliates
#
# This software is licensed under the terms of the Cisco Sample Code License (CSCL)
# available here: https://developer.cisco.com/site/license/cisco-sample-code-license/

---
- name: configure an example tunnel
  hosts: localhost
  vars_files: ../../vars.yml
  tasks:

  - name: delete a previous software vrf if exists
    ignore_errors: yes
    uri:
      url: https://10.67.0.2/restconf/data/ipsecclient:api/vrf=3
      method: DELETE
      force_basic_auth: yes
      user: "{{ ipsecclient_username }}"
      password: "{{ ipsecclient_password }}"
      validate_certs: no

  - name: template the configuration json
    ansible.builtin.template:
      src: sw_create.json.j2
      dest: sw_create.json

  - name: create a software vrf
    uri:
      url: https://10.67.0.2/restconf/data/ipsecclient:api/vrf
      method: POST
      status_code: [200, 201]
      force_basic_auth: yes
      user: "{{ ipsecclient_username }}"
      password: "{{ ipsecclient_password }}"
      src: sw_create.json
      validate_certs: no
