#!/bin/bash
curl -v -XPUT http://localhost/api/vrfs/65535 -u "admin:cisco123" -d @- << EOF
{
   "id":65535,
   "client_name":"hardware",
   "vlan":123,
   "crypto_ph1":[
      "aes-cbc-128",
      "sha256",
      "fourteen"
   ],
   "crypto_ph2":[
      "esp-aes",
      "esp-sha256-hmac",
      "group144"
   ],
   "physical_interface":"eth0",
   "active":true,
   "local_as":123,
   "lan_ip":"10.0.0.1",
   "endpoints":[
      {
         "remote_ip_sec":"10.1.0.1",
         "local_ip":"10.2.0.1",
         "peer_ip":"10.3.0.1",
         "psk":"asdasdasdasd",
         "nat":true,
         "bgp":true,
         "remote_as":321,
         "source_interface":"GigabitEthernet1"
      }
   ]
}
EOF

