# Copyright (c) 2021 Cisco and/or its affiliates
#
# This software is licensed under the terms of the Cisco Sample Code License (CSCL)
# available here: https://developer.cisco.com/site/license/cisco-sample-code-license/

---
- name: configure an example tunnel
  hosts: localhost
  vars_files: ../vars.yml
  tasks:

  - name: delete a previous software vrf if exists
    ignore_errors: yes
    uri:
      url: http://localhost:9100/restconf/data/ipsecclient:api/vrf=2
      method: DELETE
      status_code: [200, 204]
      force_basic_auth: yes
      user: "{{ ipsecclient_username }}"
      password: "{{ ipsecclient_password }}"

  - name: create a software vrf
    uri:
      url: http://localhost:9100/restconf/data/ipsecclient:api/vrf
      method: POST
      status_code: [200, 201]
      force_basic_auth: yes
      user: "{{ ipsecclient_username }}"
      password: "{{ ipsecclient_password }}"
      src: sw_create.json

  - name: configure the hardware
    uri:
      url: http://localhost:9100/restconf/data/ipsecclient:api/vrf=1
      method: PATCH
      status_code: [200, 204]
      force_basic_auth: yes
      user: "{{ ipsecclient_username }}"
      password: "{{ ipsecclient_password }}"
      src: hw.json
