version: '3.7'
services:
  ipsec-1:
    container_name: site1
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site1
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.67.0.101

  ipsec-2:
    container_name: site2
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site2
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.67.0.102

  ipsec-3:
    container_name: site3
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site3
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.67.0.103

  ipsec-4:
    container_name: site4
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site4
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.67.0.104

  ipsec-5:
    container_name: site5
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site5
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.67.0.105

  ipsec-6:
    container_name: site6
    build:
      context: strongswan
      dockerfile: Dockerfile
      args:
        CONFIG: site6
    privileged: yes
    restart: always
    networks:
      ipsec:
        ipv4_address: 10.67.0.106

  bird-1:
    container_name: bird1
    pid: service:ipsec-1
    network_mode: service:ipsec-1
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site1

  bird-2:
    container_name: bird2
    pid: service:ipsec-2
    network_mode: service:ipsec-2
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site2

  bird-3:
    container_name: bird3
    pid: service:ipsec-3
    network_mode: service:ipsec-3
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site3

  bird-4:
    container_name: bird4
    pid: service:ipsec-4
    network_mode: service:ipsec-4
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site4

  bird-5:
    container_name: bird5
    pid: service:ipsec-5
    network_mode: service:ipsec-5
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site5

  bird-6:
    container_name: bird6
    pid: service:ipsec-6
    network_mode: service:ipsec-6
    privileged: yes
    build:
      context: bird
      dockerfile: Dockerfile
      args:
        CONFIG: site6

networks:
  ipsec:
    name: aipsec
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ipsec_br
      com.docker.network.bridge.enable_icc: "true"
    ipam:
      config:
        - subnet: 10.67.0.0/24
