---
- name: configure an example tunnel
  hosts: localhost
  vars_files: ../vars.yml
  tasks:

  - name: delete a previous software vrf if exists
    ignore_errors: yes
    uri:
      url: https://localhost/restconf/data/sico-ipsec:api/vrf=2
      method: DELETE
      status_code: [200, 204]
      force_basic_auth: yes
      user: "{{ sico_username }}"
      password: "{{ sico_password }}"
      validate_certs: no

  - name: create a software vrf
    uri:
      url: https://localhost/restconf/data/sico-ipsec:api/vrf
      method: POST
      status_code: [200, 201]
      force_basic_auth: yes
      user: "{{ sico_username }}"
      password: "{{ sico_password }}"
      src: sw_create.json
      validate_certs: no

  - name: configure the hardware
    uri:
      url: https://localhost/restconf/data/sico-ipsec:api/vrf=1
      method: PATCH
      status_code: [200, 204]
      force_basic_auth: yes
      user: "{{ sico_username }}"
      password: "{{ sico_password }}"
      src: hw.json
      validate_certs: no
